apiVersion: 0.1.0
environments:
  default:
    destination:
      namespace: ks-dev
      server: https://api-k8-rkesani-cluster-k8-uo6naq-1716195002.us-west-2.elb.amazonaws.com
    k8sVersion: v1.10.0
    path: default
kind: ksonnet.io/app
name: guestbook
registries:
  incubator:
    gitVersion:
      commitSha: 40285d8a14f1ac5787e405e1023cf0c07f6aa28c
      refSpec: master
    protocol: github
    uri: github.com/ksonnet/parts/tree/master/incubator
version: 0.0.1
